### ISSUE TITLE
JavaScript interop calls Exception 

### ISSUE THREAD

**Issue by DiyarBakir** [neozhu/CleanArchitectureWithBlazorServer#148]
During first page hard reload or page refresh the application try to call JavaScript interop  which the connection have not established yet so it return the following exception

````bash
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
   at CleanArchitecture.Blazor.Infrastructure.Services.Authentication.IdentityAuthenticationService.GetAuthenticationStateAsync() in C:\Dev\CleanArchitectureWithBlazorServer\src\Infrastructure\Services\Authentication\IdentityAuthenticationService.cs:line 32
````

Exception fired at **storedClaimsIdentity**

````csharp

 public override async Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        var principal = new ClaimsPrincipal(new ClaimsIdentity());
        try
        {
            var storedClaimsIdentity = await _protectedLocalStorage.GetAsync<string>(LocalStorage.CLAIMSIDENTITY);
            if (storedClaimsIdentity.Success && storedClaimsIdentity.Value is not null)
            {
                var buffer = Convert.FromBase64String(storedClaimsIdentity.Value);
                using (var deserializationStream = new MemoryStream(buffer))
                {
                    var identity = new ClaimsIdentity(new BinaryReader(deserializationStream, Encoding.UTF8));
                    principal = new(identity);
                }
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
        return new AuthenticationState(principal);
    }

````

**Comment by neozhu** [comment]
I know this issue, the reason is that server-side blazor application can not call javascript when the page loading.
so it can only write try-catch to the handler with this.
Do you have any good solution?

**Comment by DiyarBakir** [comment]
unfortunately, no solution at the moment, when it comes I will fix it.
