### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by kirkey** [neozhu/CleanArchitectureWithBlazorServer#230]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CleanArchitecture.Blazor.Application.Common.Extensions.DescriptionAttributeExtensions.GetMemberDescription[T](T t, String memberName) in ..\src\Application\Common\Extensions\DescriptionAttributeExtensions.cs:line 27
   at Blazor.Server.UI.Pages.SMS.MessageIns.MessageIns.<>c__DisplayClass0_0.<BuildRenderTree>b__47(RenderTreeBuilder __builder3)
   at MudBlazor.MudTable`1.<>c__DisplayClass147_2.<BuildRenderTree>b__12(RenderTreeBuilder __builder4)
   at MudBlazor.MudTr.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by neozhu** [comment]
thank you for feedback
