### ISSUE TITLE
not run in iis express

### ISSUE THREAD

**Issue by willymartinez93** [neozhu/CleanArchitectureWithBlazorServer#455]
when i change the connectionstring to sqlserver then to run the blazor.ui project in iisexpress doesn't work. 
the error is
2023-07-25 16:22:29.043 -04:00 [ERR] Unhandled exception in circuit 'z68pXwHnWXLqw_ttWHFmdHFAHrsbdEnfSraPMoaxVhA'.
System.AggregateException: One or more errors occurred. (Sequence contains no elements.)
 ---> System.InvalidOperationException: Sequence contains no elements.
   at Fluxor.Blazor.Web.StoreInitializer.OnAfterRender(Boolean firstRender) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor.Blazor.Web\StoreInitializer.cs:line 57
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleAfterRender.OnAfterRenderAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()
   --- End of inner exception stack trace ---

**Comment by willymartinez93** [comment]
clean the localstorage works fine
