### ISSUE TITLE
Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

### ISSUE THREAD

**Issue by goldmannyc** [neozhu/CleanArchitectureWithBlazorServer#558]
Just cloned the code base, and running it.  From time to time,  got the below error,  is there a place to look into this?

[2023-11-19T00:39:46.969Z] Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at CleanArchitecture.Blazor.Server.UI.Hubs.HubClient.StartAsync(CancellationToken cancellation) in C:\SE\GitHub\CleanArchitectureWithBlazorServer\src\Server.UI\Hubs\HubClient.cs:line 74
   at CleanArchitecture.Blazor.Server.UI.Components.Identity.UserLoginState.OnInitializedAsync() in C:\SE\GitHub\CleanArchitectureWithBlazorServer\src\Server.UI\Components\Identity\UserLoginState.razor.cs:line 36
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
log @ blazor.server.js:1

**Comment by faps25** [comment]
Hi,

It worked for me, commenting the following in AccessTokenProvider:

    public async Task<ClaimsPrincipal> GetClaimsPrincipal()
    {
        try
        {
            var token = await _localStorage.GetAsync<AuthenticatedUserResponse>(_tokenKey);
            if (token.Success && token.Value is not null)
            {
                AccessToken = token.Value.AccessToken;
                RefreshToken = token.Value.RefreshToken;
                var validationResult = await _tokenValidator.ValidateTokenAsync(AccessToken!);
                if (validationResult.IsValid)
                {

                    return SetUserPropertiesFromClaimsPrincipal(new ClaimsPrincipal(validationResult.ClaimsIdentity));
                }
                //else
                //{
                //    var validationRefreshResult = await _refreshTokenValidator.ValidateTokenAsync(RefreshToken!);
                //    if (validationRefreshResult.IsValid)
                //    {

                //        return SetUserPropertiesFromClaimsPrincipal(new ClaimsPrincipal(validationRefreshResult.ClaimsIdentity));
                //    }

                //}
            }
        }
        catch (CryptographicException)
        {
            await RemoveAuthDataFromStorage();
        }
        catch (Exception)
        {
            return new ClaimsPrincipal(new ClaimsIdentity());
        }
        return new ClaimsPrincipal(new ClaimsIdentity());
    }

**Comment by neozhu** [comment]
@goldmannyc  Please try clearing the browser's Local Storage by following these steps: Press F12 -> Go to the 'Application' tab -> Navigate to 'Local Storage' -> Click on 'Clear ALL'.
