### ISSUE TITLE
Unhandled exception in circuit when application starts up - Unauthorized

### ISSUE THREAD

**Issue by baharedankoyuncu** [neozhu/CleanArchitectureWithBlazorServer#581]
Hi,

Just looking around this repository and just wanted to say that it looks really promising, well done 👏

I stumbled upon a little issue from time to time (not consistent) that I get this error in the CLI upon start up of the app in local development and the home/login page is just blank.

I haven't been able to spot the issue yet but wanted to ask if this was something known?

```
[15:33:00 ERR ::1] Unhandled exception in circuit '7dBJXGG0pLdOhb19NvlNz1mFXVfQn8ksqbKB97MMgIs'.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at BlazorApp.Server.UI.Hubs.HubClient.StartAsync(CancellationToken cancellation) in C:\Users\brk\source\repos\blazorApp\src\Server.UI\Hubs\HubClient.cs:line 74
   at BlazorApp.Server.UI.Components.Identity.UserLoginState.OnInitializedAsync() in C:\Users\brk\source\repos\blazorApp\src\Server.UI\Components\Identity\UserLoginState.razor.cs:line 36
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```

I'll have a deeper look at some point but if you have any hints it would be appreciated.

**Comment by baharedankoyuncu** [comment]
Looking through some of the closed issues again I see that this seems to be a recurring thing. Cleaning local storage fixed the issue but I wonder what the root cause would be. I have been using MSSQL SQL Express.

**Comment by neozhu** [comment]
this issue is that the user information used to generate the token is not consistent with the information stored in the database.

**Comment by baharedankoyuncu** [comment]
What would the solution be? I’m not sure I fully understand the problem? Is it that multiple data stores are available?
