### ISSUE TITLE
Auth 401 re-fresh token issue

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#639]
Hey @neozhu as reported in #611 & #635 I keep having issues with the token not refreshing/redirecting to login. I'm going to dive into this now but also want to report it and offer solution to everyone when/if we find it.

Yesterday I deployed my app to production, earlier today I had a blank screen and this in console log and now again. (Clearing the token helps but thats not a fix for end users)
```
blazor.web.js:1 
 [2024-03-20T13:02:33.543Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'
```
Set it to true and
```
blazor.web.js:1  [2024-03-20T13:14:46.262Z] Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at XVI2.Server.UI.Hubs.HubClient.StartAsync(CancellationToken cancellation) in C:\Users\Jochem\Documents\XVI-2-NET8\XVI2\src\Server.UI\Hubs\HubClient.cs:line 74
   at XVI2.Server.UI.Components.Identity.UserLoginState.OnInitializedAsync() in C:\Users\Jochem\Documents\XVI-2-NET8\XVI2\src\Server.UI\Components\Identity\UserLoginState.razor.cs:line 36
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
````

Little edit: You deserve so much love for this project, I'm so happy with it!

Edit 1:

As the exception states here the exception gets thrown (but I've very little knowledge about signalr and where the actual exception is thrown)

**UserLoginState.razor**
```
        await Client.StartAsync().ConfigureAwait(false);
```

Edit 2: 

I'm curious why cause I didn't close this project really long ago but there is a difference between the UserLoginState.razor.cs class i've and is in the main repo (my version seems to be from 30-01-2024)
**Note: it's quite hard to keep up to date with everything changing in here (and having thus proper support ability)**

Edit 3:
I'm using SQL server to run this (not using in memory)
Setting up a fresh project to test/replicate issue

Edit 4:
When setting up a brand new clone of the project it seems to protect better and work better with 401's then whichever version I've (bit frustrating but good to see that with upgrading things will get solved).
A Note: When deleting the database and rebooting the app (it creates the new db) and i'm logged in with the same session as with the old database. Mainly this even works (which I think is a little bit odd) but when clicking on the user profile right above it crashes with a nullpointer.

**Comment by neozhu** [comment]
thank you for your information, I will check it.
