### ISSUE TITLE
Error when logging out.

### ISSUE THREAD

**Issue by cptzig** [neozhu/CleanArchitectureWithBlazorServer#650]
I am getting error when logging out. The server 500 error code.
And I was investingating a bit and found out that namespace
`CleanArchitecture.Blazor.Server.UI.Pages.Identity.Authentication` does not exists.

**Comment by neozhu** [comment]
I've tested and found no issues with the logout function.

**Comment by cptzig** [comment]
@neozhu 
Sorry for my late response, the error comes when I am trying to logout from the public layout.

> An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Http.BadHttpRequestException: Invalid anti-forgery token found when reading parameter "string returnUrl" from the request body as form.
 ---> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Log.InvalidAntiforgeryToken(HttpContext httpContext, String parameterTypeName, String parameterName, Exception exception, Boolean shouldThrow)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForForm>g__TryReadFormAsync|104_0(HttpContext httpContext, String parameterTypeName, String parameterName, Boolean throwOnBadRequest)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass104_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
[09:48:40 ERR ::1] Could not process a request on machine User. TraceId: 00-71b92d90fd78d293acb1c723a6884782
Microsoft.AspNetCore.Http.BadHttpRequestException: Invalid anti-forgery token found when reading parameter "string returnUrl" from the request body as form.
 ---> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Log.InvalidAntiforgeryToken(HttpContext httpContext, String parameterTypeName, String parameterName, Exception exception, Boolean shouldThrow)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForForm>g__TryReadFormAsync|104_0(HttpContext httpContext, String parameterTypeName, String parameterName, Boolean throwOnBadRequest)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass104_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by neozhu** [comment]
Please pull the latest version from the main branch and try again; I tested it here and there were no issues.

**Comment by cptzig** [comment]
I tested again from a clean clone, and I still get this error, which is super weird as we are getting different results. However, if I figure out why I will update in this issue.

**Comment by neozhu** [comment]
Could you check the database being used to see if there is a table named [DataProtectionKeys]?
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/821c1ccf-aab3-4f37-b89f-864e9e27fa7b)

**Comment by cptzig** [comment]
yes it does exist,
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/42944941/825ff88b-2ae9-4d44-85ea-a37e2a22c5cc)

**Comment by neozhu** [comment]
see there, I think this is a bug.
<img width="880" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/b2067551-4195-4daa-a27b-e35b795f2fe1">

**Comment by cptzig** [comment]
Is this error occurring only to me?
To my understanding this is related to the AntiforgeryToken in `src/Server.UI/Components/Shared/Layout/PublicLayout.razor`, but as it can be seen at the picture below, the token should be provide by `<AntiforgeryToken/>`
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/42944941/b037d486-1e3e-42cd-8975-85175647883f)

**Comment by cptzig** [comment]
Yes I see the token, but I still don't get it why this error persists. However I will let it be as for now, and debug further in another time.
