### ISSUE TITLE
Error on updating user preferences

### ISSUE THREAD

**Issue by rwxzig** [neozhu/CleanArchitectureWithBlazorServer#742]
I tried to update user preferences, in this case was color, and this error was raised:
```
Unhandled exception in circuit 'spGgebTW_qml-XR5OJO4YrU6ZokEE0vHDnp6Csjcy9A'.
System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at CleanArchitecture.Blazor.Server.UI.Components.Shared.Layout.MainLayout.LayoutServiceOnMajorUpdateOccured(Object sender, EventArgs e) in CleanArchitectureWithBlazorServer\src\Server.UI\Components\Shared\Layout\MainLayout.razor:line 53
   at CleanArchitecture.Blazor.Server.UI.Services.Layout.LayoutService.OnMajorUpdateOccured() in CleanArchitectureWithBlazorServer\src\Server.UI\Services\Layout\LayoutService.cs:line 113
   at CleanArchitecture.Blazor.Server.UI.Services.Layout.LayoutService.UpdateUserPreferences(UserPreference preferences) in CleanArchitectureWithBlazorServer\src\Server.UI\Services\Layout\LayoutService.cs:line 279
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at CleanArchitecture.Blazor.Server.UI.Components.Shared.Themes.ThemesMenu.UpdateThemePrimaryColor(String color) in CleanArchitectureWithBlazorServer\src\Server.UI\Components\Shared\Themes\ThemesMenu.razor:line 224
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by neozhu** [comment]
fixed
