### ISSUE TITLE
Redirect to Home

### ISSUE THREAD

**Issue by BogdanJak** [neozhu/CleanArchitectureWithBlazorServer#791]
Hi

RedirectToHome has stopped working when the same user logs in multiple times a day.
Unless that's the intended effect?

Bogdan

**Comment by neozhu** [comment]
Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
 ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

like this? I don't know why this problem occurs, maybe it is the network delay

**Comment by neozhu** [comment]
it should be fixed
