### ISSUE TITLE
IHttpContextAccessor must be avoided.

### ISSUE THREAD

**Issue by veerendra-shakya** [neozhu/CleanArchitectureWithBlazorServer#803]
The current implementation of the application uses IHttpContextAccessor in several places, leading to issues when hosting on a non-Windows environment (e.g., Linux Ubuntu Server). This causes the IHttpContextAccessor to always return null, resulting in SignalR hub connection failures and errors on various pages.

Affected Components:

- HubClient.cs
- CurrentUserService.cs
- UserMenu.razor
- SerilogExtension.cs

Microsoft Recommendation: Microsoft advises avoiding the use of IHttpContextAccessor in Blazor Server applications wherever possible 
[reference documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-9.0&tabs=visual-studio)

![image](https://github.com/user-attachments/assets/dce921f1-5a12-49e7-bc6a-53ffa69219c4)

Steps to Reproduce:

- Deploy the application on a Linux Ubuntu server.
- Run the application and try to connect to a SignalR hub.
- Observe the errors related to IHttpContextAccessor being null.

**Comment by neozhu** [comment]
I understand that using IHttpContextAccessor in Blazor Server can cause problems on Linux, leading to SignalR connection failures. Microsoft also recommends avoiding it in Blazor Server projects.

When I deploy the app using a Docker container, I don't see this problem. I will work on replacing IHttpContextAccessor when I have time.

**Comment by veerendra-shakya** [comment]
today i tried to publish it on windows server with IIS,  unfortunately it is not running on Windows Server also

Developers Tool Console 
![image](https://github.com/user-attachments/assets/be004eda-b3b2-4575-8cef-18f02863bd89)

LOG FILE:

2024-12-09 17:29:54.057 +05:30 [INF] administrator has logged in.
2024-12-09 17:29:55.222 +05:30 [ERR] Unhandled exception in circuit 'rqR6C5tFIbqgbo_mkq8E7tI0SiA2mAcJBfOoA1F2h8k'.
System.InvalidOperationException: HttpContext is not available.
   at Acadmically.Server.UI.Components.Shared.Layout.UserMenu.getAntiforgeryToken() in D:\GIT_Projects\2024_Acadmically\Acadmically\src\Server.UI\Components\Shared\Layout\UserMenu.razor:line 94
   at Acadmically.Server.UI.Components.Shared.Layout.UserMenu.OnInitialized() in D:\GIT_Projects\2024_Acadmically\Acadmically\src\Server.UI\Components\Shared\Layout\UserMenu.razor:line 87
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-12-09 17:29:55.245 +05:30 [ERR] Unhandled exception in circuit 'rqR6C5tFIbqgbo_mkq8E7tI0SiA2mAcJBfOoA1F2h8k'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-12-09 17:30:00.712 +05:30 [ERR] Unhandled exception in circuit 'BvRm0SB8UOc6OVOgkf5UxfJN6rIUlnnZZ94eB2KoMWE'.
System.InvalidOperationException: HttpContext is not available.
   at Acadmically.Server.UI.Components.Shared.Layout.UserMenu.getAntiforgeryToken() in D:\GIT_Projects\2024_Acadmically\Acadmically\src\Server.UI\Components\Shared\Layout\UserMenu.razor:line 94
   at Acadmically.Server.UI.Components.Shared.Layout.UserMenu.OnInitialized() in D:\GIT_Projects\2024_Acadmically\Acadmically\src\Server.UI\Components\Shared\Layout\UserMenu.razor:line 87
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-12-09 17:30:00.714 +05:30 [ERR] Unhandled exception in circuit 'BvRm0SB8UOc6OVOgkf5UxfJN6rIUlnnZZ94eB2KoMWE'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by veerendra-shakya** [comment]
Thanks, but still facing error on publish 

Issue: Hub Connection Timeout on Published Server

I encountered an issue with the latest version of the repository when publishing the application to a Windows server. The Hub connection fails with a timeout error after approximately 30 seconds.

your application is live on this domain: https://academically.in/ please login and watch the console.

Here’s the error log from the console:

![image](https://github.com/user-attachments/assets/54ef76b6-09d2-49e5-92e4-82f4f2295600)
